[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
estima = { path = "../estima" }
estimacros = { path = "../estimacros" }

[[example]]
name = "vector_union"
path = "vector_union.rs"

[[example]]
name = "cvm"
path = "cvm.rs"