[package]
name = "estima"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
nalgebra = { version = "0.33.2", default-features = false, features = ["libm"] }
typenum = "1.18.0"

[dev-dependencies]
approx = "0.5.1"
