[package]
name = "estima"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
nalgebra = { version = "0.33.2", default-features = false, features = ["libm"] }
typenum = "1.18.0"

[dev-dependencies]
approx = "0.5.1"
rerun = "0.24.0"
rand = "0.8.5"
ndarray = "0.16.1"

[[example]]
name = "cv_ukf"
path = "examples/cv_ukf.rs"
